/**
 * ChatGPT Context Monitor - Build & Bundle Script
 * 
 * Bundles modular ES modules into a self-contained content script
 * for reliable loading in Chrome Manifest V3 content script context.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

console.log('[Build] Packaging ChatGPT Context Monitor content script...');

// Read model limits JSON
const modelLimitsRaw = fs.readFileSync(path.join(rootDir, 'config', 'model-limits.json'), 'utf8');

// Read js-tiktoken runtime and ranks
const base64Code = fs.readFileSync(path.join(rootDir, 'node_modules', 'base64-js', 'index.js'), 'utf8')
  .replace('exports.byteLength = byteLength', '')
  .replace('exports.toByteArray = toByteArray', '')
  .replace('exports.fromByteArray = fromByteArray', '');

const chunkCode = fs.readFileSync(path.join(rootDir, 'node_modules', 'js-tiktoken', 'dist', 'chunk-VL2OQCWN.js'), 'utf8')
  .replace("import base64 from 'base64-js';", '')
  .replace(/export\s*\{[^}]+\};?/g, '');

const cl100kRaw = fs.readFileSync(path.join(rootDir, 'node_modules', 'js-tiktoken', 'dist', 'ranks', 'cl100k_base.js'), 'utf8')
  .replace('export default ', '');

const o200kRaw = fs.readFileSync(path.join(rootDir, 'node_modules', 'js-tiktoken', 'dist', 'ranks', 'o200k_base.js'), 'utf8')
  .replace('export default ', '');

const tiktokenInlined = `
  // --- Inlined js-tiktoken core & ranks ---
  const base64 = (function() {
    const exports = {};
    ${base64Code}
    return { toByteArray, fromByteArray };
  })();

  ${chunkCode}

  const cl100k_base = ${cl100kRaw.trim()};
  const o200k_base = ${o200kRaw.trim()};
`;

// Helper to read and clean module syntax for inlining into content script IIFE
function readCleanModule(filePath) {
  return fs.readFileSync(filePath, 'utf8')
    .replace(/import\s+[^;]+from\s+[^;]+;/g, '')
    .replace(/export\s*\{[^}]+\};?/g, '')
    .replace(/export\s+default\s+/g, '')
    .replace(/export\s+/g, '');
}

// Read modules
const tokenizerCode = readCleanModule(path.join(rootDir, 'engine', 'tokenizer.js'));
const classifierCode = readCleanModule(path.join(rootDir, 'engine', 'context-classifier.js'));
const mergerCode = readCleanModule(path.join(rootDir, 'engine', 'evidence-merger.js'));
const confidenceCode = readCleanModule(path.join(rootDir, 'engine', 'confidence-engine.js'));
const calculatorCode = readCleanModule(path.join(rootDir, 'engine', 'context-calculator.js'));
const extractorCode = readCleanModule(path.join(rootDir, 'content', 'message-extractor.js'));
const planDetectorCode = readCleanModule(path.join(rootDir, 'content', 'plan-detector.js'));
const detectorCode = readCleanModule(path.join(rootDir, 'content', 'model-detector.js'));
const conversationClientCode = readCleanModule(path.join(rootDir, 'content', 'conversation-client.js'));
const attachmentCode = readCleanModule(path.join(rootDir, 'content', 'attachment-detector.js'));
const toolCode = readCleanModule(path.join(rootDir, 'content', 'tool-detector.js'));
const widgetStateCode = readCleanModule(path.join(rootDir, 'content', 'widget-state.js'));
const overlayCode = readCleanModule(path.join(rootDir, 'content', 'overlay-ui.js'));
const domObserverCode = readCleanModule(path.join(rootDir, 'content', 'chatgpt-dom.js'));
const requestObserverCode = readCleanModule(path.join(rootDir, 'network', 'request-observer.js'));
const turnMergerCode = readCleanModule(path.join(rootDir, 'content', 'turn-merger.js'));
const contentMainCode = readCleanModule(path.join(rootDir, 'content', 'content-main.js'));

const bundledContentScript = `/**
 * ChatGPT Context Monitor - Production Content Script
 * Auto-generated by scripts/build.js. Do not edit directly.
 * 
 * Complies with Chrome Manifest V3 Content Script standards:
 * - Isolated world execution
 * - Non-blocking main-thread debounced DOM extraction
 * - 100% offline local tokenization
 */

(function() {
  'use strict';

  // Embedded verified model limits configuration
  const MODEL_LIMITS_DB = ${modelLimitsRaw.trim()};

  // --- Inlined Tiktoken BPE Engine ---
  ${tiktokenInlined}

  // --- Engine Layer ---
  ${tokenizerCode}

  ${classifierCode}

  ${mergerCode}

  ${confidenceCode}

  ${calculatorCode}

  // --- Network Layer ---
  ${requestObserverCode}

  // --- Content & DOM Adapters ---
  ${conversationClientCode}

  ${extractorCode}

  ${planDetectorCode}

  ${detectorCode}

  ${attachmentCode}

  ${toolCode}

  ${widgetStateCode}

  ${overlayCode}

  ${domObserverCode}

  ${turnMergerCode}

  ${contentMainCode}

  // Auto-initialize when loaded on ChatGPT Web
  try {
    const coordinator = new ContentScriptCoordinator(MODEL_LIMITS_DB);
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', () => coordinator.init());
    } else {
      coordinator.init();
    }
  } catch (err) {
    console.error('[ChatGPT Context Monitor] Failed to initialize:', err);
  }
})();
`;

// Validate bundled content script syntax before writing
try {
  new Function(bundledContentScript);
} catch (syntaxErr) {
  console.error('[Build Error] Syntax error in bundled content script:', syntaxErr);
  process.exit(1);
}

fs.writeFileSync(path.join(rootDir, 'content', 'content-script.js'), bundledContentScript, 'utf8');
console.log('[Build] Successfully generated content/content-script.js (' + (bundledContentScript.length / 1024).toFixed(1) + ' KB)');
