/**
 * ChatGPT Context Monitor - Build & Bundle Script
 * 
 * Bundles modular ES modules into a self-contained content script
 * for reliable loading in Chrome Manifest V3 content script context.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

console.log('[Build] Packaging ChatGPT Context Monitor content script...');

// Read model limits JSON
const modelLimitsRaw = fs.readFileSync(path.join(rootDir, 'config', 'model-limits.json'), 'utf8');

// Read modules
const tokenizerCode = fs.readFileSync(path.join(rootDir, 'engine', 'tokenizer.js'), 'utf8')
  .replace(/export\s+/g, '');

const classifierCode = fs.readFileSync(path.join(rootDir, 'engine', 'context-classifier.js'), 'utf8')
  .replace(/export\s+/g, '');

const confidenceCode = fs.readFileSync(path.join(rootDir, 'engine', 'confidence-engine.js'), 'utf8')
  .replace(/export\s+/g, '');

const calculatorCode = fs.readFileSync(path.join(rootDir, 'engine', 'context-calculator.js'), 'utf8')
  .replace(/import\s+.*?from\s+.*?;/g, '')
  .replace(/export\s+/g, '');

const extractorCode = fs.readFileSync(path.join(rootDir, 'content', 'message-extractor.js'), 'utf8')
  .replace(/export\s+/g, '');

const detectorCode = fs.readFileSync(path.join(rootDir, 'content', 'model-detector.js'), 'utf8')
  .replace(/export\s+/g, '');

const attachmentCode = fs.readFileSync(path.join(rootDir, 'content', 'attachment-detector.js'), 'utf8')
  .replace(/export\s+/g, '');

const toolCode = fs.readFileSync(path.join(rootDir, 'content', 'tool-detector.js'), 'utf8')
  .replace(/export\s+/g, '');

const overlayCode = fs.readFileSync(path.join(rootDir, 'content', 'overlay-ui.js'), 'utf8')
  .replace(/export\s+/g, '');

const domObserverCode = fs.readFileSync(path.join(rootDir, 'content', 'chatgpt-dom.js'), 'utf8')
  .replace(/export\s+/g, '');

const contentMainCode = fs.readFileSync(path.join(rootDir, 'content', 'content-main.js'), 'utf8')
  .replace(/import\s+.*?from\s+.*?;/g, '')
  .replace(/export\s+/g, '');

const bundledContentScript = `/**
 * ChatGPT Context Monitor - Production Content Script
 * Auto-generated by scripts/build.js. Do not edit directly.
 * 
 * Complies with Chrome Manifest V3 Content Script standards:
 * - Isolated world execution
 * - Non-blocking main-thread debounced DOM extraction
 * - 100% offline local tokenization
 */

(function() {
  'use strict';

  // Embedded verified model limits configuration
  const MODEL_LIMITS_DB = ${modelLimitsRaw.trim()};

  // --- Engine Layer ---
  ${tokenizerCode}

  ${classifierCode}

  ${confidenceCode}

  ${calculatorCode}

  // --- Content & DOM Adapters ---
  ${extractorCode}

  ${detectorCode}

  ${attachmentCode}

  ${toolCode}

  ${overlayCode}

  ${domObserverCode}

  ${contentMainCode}

  // Auto-initialize when loaded on ChatGPT Web
  try {
    const coordinator = new ContentScriptCoordinator(MODEL_LIMITS_DB);
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', () => coordinator.init());
    } else {
      coordinator.init();
    }
  } catch (err) {
    console.error('[ChatGPT Context Monitor] Failed to initialize:', err);
  }
})();
`;

fs.writeFileSync(path.join(rootDir, 'content', 'content-script.js'), bundledContentScript, 'utf8');
console.log('[Build] Successfully generated content/content-script.js (' + (bundledContentScript.length / 1024).toFixed(1) + ' KB)');
